server:
  port: ${PORT:8080}

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: chaerok-be

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

supabase:
  url: ${SUPABASE_URL}
  storage:
    bucket: ${SUPABASE_STORAGE_BUCKET}
  service-role-key: ${SUPABASE_SERVICE_ROLE_KEY}

external:
  kakao:
    api-key: ${KAKAO_API_KEY}
  tour-api:
    key: ${TOUR_API_KEY}
  odii:
    key: ${ODII_API_KEY}

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    admin-key: ${KAKAO_ADMIN_KEY}
    issuer: https://kauth.kakao.com
    jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json

  google:
    client-id: ${GOOGLE_CLIENT_ID}
    issuer: https://accounts.google.com
    jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}
  signup-expiration: ${JWT_SIGNUP_EXPIRATION}