CREATE TABLE photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    region_id BIGINT NOT NULL,
    original_image_url TEXT NOT NULL,
    filtered_image_url TEXT NOT NULL,
    filter_id VARCHAR(100) NOT NULL,
    filter_strength DOUBLE PRECISION NOT NULL,
    taken_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_photos_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_photos_region
        FOREIGN KEY (region_id)
            REFERENCES regions (id)
);