-- V10의 photos 테이블은 아직 실제 서비스 데이터가 없는 개발 단계라는 전제에서
-- Lambda 비동기 현상 구조에 맞게 재구성합니다.
-- 데이터가 존재하면 자동 삭제하지 않고 마이그레이션을 중단합니다.
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM photos) THEN
        RAISE EXCEPTION
            'V11 migration aborted: photos table contains data. Back up or migrate existing rows before applying V11.';
    END IF;
END
$$;

DROP TABLE photos;

CREATE TABLE film_rolls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,
    region_id BIGINT NOT NULL,

    filter_id VARCHAR(100) NOT NULL,
    filter_strength DOUBLE PRECISION NOT NULL,
    filter_version INTEGER NOT NULL DEFAULT 1,

    status VARCHAR(30) NOT NULL,

    total_photo_count INTEGER NOT NULL DEFAULT 0,
    processed_photo_count INTEGER NOT NULL DEFAULT 0,

    zip_object_key TEXT,
    reel_object_key TEXT,

    error_code VARCHAR(100),
    error_message TEXT,

    requested_at TIMESTAMP,
    completed_at TIMESTAMP,
    expires_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_film_rolls_user
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE,

    CONSTRAINT fk_film_rolls_region
        FOREIGN KEY (region_id)
            REFERENCES regions(id),

    CONSTRAINT ck_film_rolls_filter_strength
        CHECK (filter_strength >= 0.0 AND filter_strength <= 1.0),

    CONSTRAINT ck_film_rolls_filter_version
        CHECK (filter_version >= 1),

    CONSTRAINT ck_film_rolls_photo_counts
        CHECK (
            total_photo_count >= 0
            AND total_photo_count <= 24
            AND processed_photo_count >= 0
            AND processed_photo_count <= total_photo_count
        )
);

CREATE INDEX idx_film_rolls_user_status
    ON film_rolls(user_id, status);

CREATE INDEX idx_film_rolls_region_status
    ON film_rolls(region_id, status);

CREATE TABLE photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    film_roll_id BIGINT NOT NULL,
    sequence INTEGER NOT NULL,

    original_object_key TEXT NOT NULL,
    filtered_object_key TEXT,

    status VARCHAR(30) NOT NULL,
    has_face BOOLEAN NOT NULL DEFAULT FALSE,
    scene_type VARCHAR(30),

    taken_at TIMESTAMP NOT NULL,
    upload_completed_at TIMESTAMP,
    processed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    error_code VARCHAR(100),
    error_message TEXT,

    CONSTRAINT fk_photos_film_roll
        FOREIGN KEY (film_roll_id)
            REFERENCES film_rolls(id)
            ON DELETE CASCADE,

    CONSTRAINT uk_photos_film_roll_sequence
        UNIQUE (film_roll_id, sequence),

    CONSTRAINT ck_photos_sequence
        CHECK (sequence >= 1 AND sequence <= 24)
);

CREATE INDEX idx_photos_film_roll_status
    ON photos(film_roll_id, status);

CREATE TABLE render_jobs (
    id UUID PRIMARY KEY,

    film_roll_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,

    error_code VARCHAR(100),
    error_message TEXT,

    queued_at TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_render_jobs_film_roll
        FOREIGN KEY (film_roll_id)
            REFERENCES film_rolls(id)
            ON DELETE CASCADE,

    CONSTRAINT ck_render_jobs_attempt_count
        CHECK (attempt_count >= 0)
);

CREATE INDEX idx_render_jobs_film_roll_created_at
    ON render_jobs(film_roll_id, created_at DESC);

CREATE INDEX idx_render_jobs_status
    ON render_jobs(status);

-- 한 필름 롤에 동시에 진행 중인 작업은 하나만 허용합니다.
-- FAILED/COMPLETED 이후에는 새 작업을 생성할 수 있어 재시도 이력이 보존됩니다.
CREATE UNIQUE INDEX uk_render_jobs_film_roll_active
    ON render_jobs(film_roll_id)
    WHERE status IN ('CREATED', 'QUEUED', 'PROCESSING');
