CREATE TABLE visits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    film_roll_id BIGINT NOT NULL,
    place_id BIGINT NOT NULL,

    -- 방문 당시의 상위 장소 유형을 보존합니다.
    -- Place 분류가 이후 동기화로 변경돼도 과거 FilmRoll 진행도는 유지됩니다.
    category_group VARCHAR(30) NOT NULL,

    visited_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_visits_film_roll
        FOREIGN KEY (film_roll_id)
            REFERENCES film_rolls(id)
            ON DELETE CASCADE,

    CONSTRAINT fk_visits_place
        FOREIGN KEY (place_id)
            REFERENCES places(id)
            ON DELETE RESTRICT,

    CONSTRAINT uk_visits_film_roll_place
        UNIQUE (film_roll_id, place_id)
);

-- UNIQUE(film_roll_id, place_id)의 선두 컬럼이 film_roll_id이므로
-- FilmRoll별 조회와 중복 확인에는 해당 인덱스를 그대로 사용합니다.
-- Place 삭제/참조 확인용 역방향 조회를 위해 place_id 인덱스만 추가합니다.
CREATE INDEX idx_visits_place_id
    ON visits(place_id);
