CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       provider VARCHAR(20) NOT NULL,
                       provider_user_id VARCHAR(255) NOT NULL,
                       nickname VARCHAR(30) NOT NULL,
                       email VARCHAR(255),
                       created_at TIMESTAMP NOT NULL,
                       role VARCHAR(20) NOT NULL,
                       terms_agreed_at TIMESTAMP NOT NULL,
                       privacy_agreed_at TIMESTAMP NOT NULL,
                       terms_version VARCHAR(20) NOT NULL,
                       privacy_version VARCHAR(20) NOT NULL,

                       CONSTRAINT uk_users_provider_provider_user_id
                           UNIQUE (provider, provider_user_id)
);