CREATE TABLE push_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    fcm_registration_token TEXT NOT NULL,
    platform VARCHAR(20) NOT NULL,
    last_registered_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_push_devices_user
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE,

    CONSTRAINT uk_push_devices_fcm_registration_token
        UNIQUE (fcm_registration_token)
);

CREATE INDEX idx_push_devices_user_id
    ON push_devices(user_id);

CREATE TABLE notification_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_key VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    film_roll_id BIGINT NOT NULL,
    render_job_id UUID NOT NULL,
    type VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    occurred_at TIMESTAMP NOT NULL,
    next_attempt_at TIMESTAMP,
    last_error_code VARCHAR(100),
    last_error_message TEXT,
    sent_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT uk_notification_outbox_event_key
        UNIQUE (event_key),

    CONSTRAINT fk_notification_outbox_user
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE,

    CONSTRAINT fk_notification_outbox_film_roll
        FOREIGN KEY (film_roll_id)
            REFERENCES film_rolls(id)
            ON DELETE CASCADE,

    CONSTRAINT fk_notification_outbox_render_job
        FOREIGN KEY (render_job_id)
            REFERENCES render_jobs(id)
            ON DELETE CASCADE,

    CONSTRAINT ck_notification_outbox_attempt_count
        CHECK (attempt_count >= 0)
);

CREATE INDEX idx_notification_outbox_pending
    ON notification_outbox(status, next_attempt_at, created_at);