CREATE TABLE regions (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         province_name VARCHAR(20) NOT NULL,
                         city_county_name VARCHAR(20) NOT NULL,
                         ldong_regn_cd VARCHAR(10) NOT NULL,
                         ldong_signgu_cd VARCHAR(10) NOT NULL,
                         service_enabled BOOLEAN NOT NULL,

                         CONSTRAINT uk_regions_province_city_county
                             UNIQUE (province_name, city_county_name),

                         CONSTRAINT uk_regions_ldong_codes
                             UNIQUE (ldong_regn_cd, ldong_signgu_cd)
);