CREATE TABLE places (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                        region_id BIGINT NOT NULL,

                        tour_content_id VARCHAR(50) NOT NULL,

                        title VARCHAR(255) NOT NULL,
                        address VARCHAR(255),
                        latitude DECIMAL(10, 7),
                        longitude DECIMAL(10, 7),
                        first_image_url VARCHAR(500),

                        ldong_regn_cd VARCHAR(10),
                        ldong_signgu_cd VARCHAR(10),

                        lcls_systm1 VARCHAR(20),
                        lcls_systm2 VARCHAR(20),
                        lcls_systm3 VARCHAR(20),

                        category_group VARCHAR(30) NOT NULL,
                        category_detail VARCHAR(30),

                        is_representative BOOLEAN NOT NULL DEFAULT FALSE,
                        source VARCHAR(30) NOT NULL,

                        created_at TIMESTAMP NOT NULL,
                        updated_at TIMESTAMP NOT NULL,

                        CONSTRAINT fk_places_region
                            FOREIGN KEY (region_id)
                                REFERENCES regions (id),

                        CONSTRAINT uk_places_tour_content_id
                            UNIQUE (tour_content_id)
);

CREATE INDEX idx_places_region_id ON places (region_id);